version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install build esential
          command: sudo apt-get update && apt-get -y install build-essential
      - run:
          name: Make
          command: make