version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: sudo apt-get update; sudo apt-get -y install build-essential libtool automake pkg-config git wget gettext-base
      - run: make