version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - update:
      - run:
          name: update
          command: sudo apt-get update; sudo apt-get -y install build-essential libtool automake pkg-config git wget gettext-base
          name: Make
          command: make