version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install build esential
          command: sudo apt-get update && sudo apt-get -y install build-essential
      - run:
          name: Make
          command: make